# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios_usabilitystudy', '0002_option_option_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='has_verified',
            field=models.NullBooleanField(verbose_name='Verification performed'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='instruction_duration',
            field=models.BigIntegerField(verbose_name='Instruction (Millisec)'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='overall_duration',
            field=models.BigIntegerField(verbose_name='Overall (Millisec)'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='verification_duration',
            field=models.BigIntegerField(verbose_name='Verification (Millisec)'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='verification_number',
            field=models.BigIntegerField(verbose_name='Number of verifications'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='voting_duration',
            field=models.BigIntegerField(verbose_name='Voting (Millisec)'),
        ),
    ]
