# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helios_usabilitystudy', '0003_auto_20170226_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('type', models.CharField(max_length=42, verbose_name='Type')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios_usabilitystudy.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='duration',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
