# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helios_usabilitystudy', '0004_auto_20170313_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_return_code',
            field=models.CharField(default='0000', max_length=20, unique=True, verbose_name='Return-Code'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_manipulated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='timestamp_unix',
            field=models.CharField(default='0', max_length=14, verbose_name='Unix_Timestamp'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helios_usabilitystudy.Subject'),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='type',
            field=models.CharField(max_length=80, verbose_name='Type'),
        ),
    ]
