# Generated by Django 2.0.2 on 2018-02-05 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helios_usabilitystudy', '0004_auto_20170313_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helios_usabilitystudy.Subject'),
        ),
    ]
