# Generated by Django 2.0.2 on 2018-02-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios_usabilitystudy', '0005_auto_20180205_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_return_code',
            field=models.CharField(default=123456, max_length=20, unique=True, verbose_name='Return-Code'),
            preserve_default=False,
        ),
    ]
