# Generated by Django 2.0.2 on 2018-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios_usabilitystudy', '0007_auto_20180227_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='timestamp_unix',
            field=models.CharField(default=0, max_length=14, verbose_name='Unix_Timestamp'),
            preserve_default=False,
        ),
    ]
