# Generated by Django 2.0.2 on 2018-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios_usabilitystudy', '0008_timestamp_timestamp_unix'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_manipulated',
            field=models.BooleanField(default=True),
        ),
    ]
