# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helios_usabilitystudy', '0009_subject_is_manipulated'),
        ('helios_usabilitystudy', '0005_auto_20180815_0752'),
    ]

    operations = [
    ]
