# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios_usabilitystudy', '0013_answer_sus_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='sus_total',
            field=models.FloatField(default=0.0, verbose_name='SUS Score'),
        ),
    ]
